const JOB_STATUS = Object.freeze({
    QUEUED: "QUEUED",
    RUNNING: "RUNNING",
    COMPLETED: "COMPLETED",
    FAILED: "FAILED"
});

const JOB_STAGE = Object.freeze({
    QUEUED: "QUEUED",
    VALIDATING_INPUT: "VALIDATING_INPUT",
    PREPARING_CIRCUIT_INPUT: "PREPARING_CIRCUIT_INPUT",
    GENERATING_WITNESS: "GENERATING_WITNESS",
    GENERATING_PROOF: "GENERATING_PROOF",
    VERIFYING_PROOF: "VERIFYING_PROOF",
    COMPLETED: "COMPLETED",
    FAILED: "FAILED"
});

const STAGE_PROGRESS = Object.freeze({
    [JOB_STAGE.QUEUED]: 0,
    [JOB_STAGE.VALIDATING_INPUT]: 10,
    [JOB_STAGE.PREPARING_CIRCUIT_INPUT]: 20,
    [JOB_STAGE.GENERATING_WITNESS]: 45,
    [JOB_STAGE.GENERATING_PROOF]: 75,
    [JOB_STAGE.VERIFYING_PROOF]: 90,
    [JOB_STAGE.COMPLETED]: 100,
    [JOB_STAGE.FAILED]: 100
});

module.exports = {
    JOB_STATUS,
    JOB_STAGE,
    STAGE_PROGRESS
};
